### ISSUE TITLE
Transmitter Example

### ISSUE THREAD

**Issue by goncalo-leal** [patopesto/go-sacn#1]
I would like to build a sACN transmitter using this package, however, I cannot understand how. I would like my transmitter to send discovery packets and also be able to send DMX output to multiple universes. Can you guide me through this?

**Comment by patopesto** [comment]
I'm currently implementing the transmission side for the library. Expect some updates shortly

**Comment by goncalo-leal** [comment]
I would love to help you implement it! I'm planning on using this library to finish my master's dissertation, so if you need help let me know how to contribute.

**Comment by patopesto** [comment]
Hey. I just pushed a working sender with an example if you'd like to check it out. Feel free to PR if you find any bugs.

**Comment by goncalo-leal** [comment]
Thank you! I'll check it asap
